export const raw = [
  // ===== CLASSIC / TRADITIONAL =====
  { name: "William", nicknames: ["Will", "Liam", "Billy", "Bill", "Willy"], origins: ["English", "German"], meaning: "Resolute protector", styles: ["classic"], traits: ["traditional", "established", "strong"], popularityTier: "very-common" },
  { name: "James", nicknames: ["Jamie", "Jim", "Jimmy", "Jem"], origins: ["Hebrew"], meaning: "Supplanter", styles: ["classic"], traits: ["traditional", "established", "strong"], popularityTier: "very-common" },
  { name: "Henry", nicknames: ["Hank", "Harry", "Hal", "Ry"], origins: ["German"], meaning: "Estate ruler", styles: ["classic", "vintage"], traits: ["traditional", "established", "soft"], popularityTier: "common" },
  { name: "Charles", nicknames: ["Charlie", "Chuck", "Chaz", "Chas"], origins: ["German"], meaning: "Free man", styles: ["classic"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "George", nicknames: ["Georgie"], origins: ["Greek"], meaning: "Farmer", styles: ["classic"], traits: ["traditional", "established", "soft"], popularityTier: "common" },
  { name: "Thomas", nicknames: ["Tom", "Tommy", "Tam"], origins: ["Aramaic"], meaning: "Twin", styles: ["classic"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Edward", nicknames: ["Ed", "Eddie", "Ned", "Teddy"], origins: ["English"], meaning: "Wealthy guardian", styles: ["classic", "vintage"], traits: ["traditional", "established"], popularityTier: "uncommon" },
  { name: "Robert", nicknames: ["Rob", "Robbie", "Bob", "Bobby"], origins: ["German"], meaning: "Bright fame", styles: ["classic"], traits: ["traditional", "established", "strong"], popularityTier: "common" },
  { name: "Richard", nicknames: ["Rich", "Richie", "Rick", "Ricky"], origins: ["German"], meaning: "Brave ruler", styles: ["classic"], traits: ["traditional", "strong"], popularityTier: "uncommon" },
  { name: "David", nicknames: ["Dave", "Davy"], origins: ["Hebrew"], meaning: "Beloved", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Michael", nicknames: ["Mike", "Mikey", "Mick"], origins: ["Hebrew"], meaning: "Who is like God", styles: ["classic", "biblical"], traits: ["traditional", "established", "strong"], popularityTier: "very-common" },
  { name: "Daniel", nicknames: ["Dan", "Danny"], origins: ["Hebrew"], meaning: "God is my judge", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "very-common" },
  { name: "Matthew", nicknames: ["Matt", "Matty"], origins: ["Hebrew"], meaning: "Gift of God", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Andrew", nicknames: ["Andy", "Drew"], origins: ["Greek"], meaning: "Manly, brave", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Peter", nicknames: ["Pete"], origins: ["Greek"], meaning: "Rock", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "uncommon" },
  { name: "Paul", nicknames: [], origins: ["Latin"], meaning: "Small", styles: ["classic", "biblical", "short-punchy"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Frank", nicknames: ["Frankie"], origins: ["German"], meaning: "Free man", styles: ["classic", "vintage"], traits: ["traditional", "strong"], popularityTier: "uncommon" },
  { name: "Walter", nicknames: ["Walt", "Wally"], origins: ["German"], meaning: "Ruler of the army", styles: ["vintage"], traits: ["traditional", "soft"], popularityTier: "rare" },
  { name: "Albert", nicknames: ["Al", "Bertie", "Bert"], origins: ["German"], meaning: "Noble and bright", styles: ["vintage"], traits: ["traditional", "soft"], popularityTier: "rare" },
  { name: "Arthur", nicknames: ["Art", "Artie"], origins: ["Celtic"], meaning: "Bear, noble", styles: ["classic", "vintage", "literary"], traits: ["traditional", "soft", "established"], popularityTier: "common" },

  // ===== VINTAGE / LITERARY REVIVAL =====
  { name: "Theodore", nicknames: ["Theo", "Teddy", "Ted", "Teo"], origins: ["Greek"], meaning: "Gift of God", styles: ["classic", "vintage", "literary"], traits: ["traditional", "soft", "established"], popularityTier: "common" },
  { name: "Frederick", nicknames: ["Freddie", "Fred", "Fritz", "Rick"], origins: ["German"], meaning: "Peaceful ruler", styles: ["vintage", "classic"], traits: ["traditional", "soft"], popularityTier: "uncommon" },
  { name: "Oliver", nicknames: ["Ollie", "Ol"], origins: ["Latin"], meaning: "Olive tree", styles: ["classic", "vintage"], traits: ["soft", "established"], popularityTier: "very-common" },
  { name: "Sebastian", nicknames: ["Seb", "Bash", "Bastian"], origins: ["Greek"], meaning: "Revered", styles: ["classic", "international"], traits: ["elegant", "established"], popularityTier: "common" },
  { name: "Julian", nicknames: ["Jules", "Jude", "Juli"], origins: ["Latin"], meaning: "Youthful, downy", styles: ["classic", "international"], traits: ["elegant", "soft"], popularityTier: "common" },
  { name: "Benjamin", nicknames: ["Ben", "Benji", "Benny"], origins: ["Hebrew"], meaning: "Son of the right hand", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Samuel", nicknames: ["Sam", "Sammy"], origins: ["Hebrew"], meaning: "God has heard", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Nathaniel", nicknames: ["Nate", "Nathan", "Nat"], origins: ["Hebrew"], meaning: "Gift of God", styles: ["classic", "biblical", "literary"], traits: ["traditional", "established"], popularityTier: "uncommon" },
  { name: "Alexander", nicknames: ["Alex", "Xander", "Alec", "Lex", "Sasha"], origins: ["Greek"], meaning: "Defender of the people", styles: ["classic"], traits: ["strong", "established"], popularityTier: "very-common" },
  { name: "Adrian", nicknames: ["Ade"], origins: ["Latin"], meaning: "From Hadria", styles: ["classic", "international"], traits: ["elegant"], popularityTier: "common" },
  { name: "Roman", nicknames: [], origins: ["Latin"], meaning: "Citizen of Rome", styles: ["classic", "strong", "short-punchy"], traits: ["strong"], popularityTier: "common" },
  { name: "Lucian", nicknames: ["Luca", "Luc"], origins: ["Latin"], meaning: "Light", styles: ["classic", "literary", "international"], traits: ["elegant"], popularityTier: "rare" },
  { name: "Elliot", nicknames: ["Eli"], origins: ["Hebrew"], meaning: "The Lord is my God", styles: ["classic", "literary"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Augustine", nicknames: ["Gus", "Augie"], origins: ["Latin"], meaning: "Great, magnificent", styles: ["vintage", "literary"], traits: ["elegant", "rare"], popularityTier: "rare" },
  { name: "August", nicknames: ["Gus", "Auggie"], origins: ["Latin"], meaning: "Great, magnificent", styles: ["vintage", "short-punchy"], traits: ["soft", "established"], popularityTier: "uncommon" },
  { name: "Emmett", nicknames: ["Em"], origins: ["German"], meaning: "Universal", styles: ["vintage", "short-punchy"], traits: ["soft"], popularityTier: "common" },
  { name: "Wallace", nicknames: ["Wally"], origins: ["Scottish"], meaning: "Foreigner, Welshman", styles: ["vintage"], traits: ["soft", "rare"], popularityTier: "rare" },
  { name: "Cyrus", nicknames: ["Cy"], origins: ["Persian"], meaning: "Sun, throne", styles: ["vintage", "biblical"], traits: ["strong", "rare"], popularityTier: "uncommon" },
  { name: "Silas", nicknames: [], origins: ["Latin", "Biblical"], meaning: "Forest, woods", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Elias", nicknames: ["Eli"], origins: ["Greek", "Hebrew"], meaning: "The Lord is my God", styles: ["classic", "biblical", "international"], traits: ["elegant", "established"], popularityTier: "common" },

  // ===== BIBLICAL =====
  { name: "Noah", nicknames: [], origins: ["Hebrew"], meaning: "Rest, comfort", styles: ["biblical"], traits: ["soft", "established"], popularityTier: "very-common" },
  { name: "Joseph", nicknames: ["Joe", "Joey"], origins: ["Hebrew"], meaning: "God will increase", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Isaac", nicknames: ["Ike", "Zac"], origins: ["Hebrew"], meaning: "He will laugh", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Jacob", nicknames: ["Jake"], origins: ["Hebrew"], meaning: "Supplanter", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "very-common" },
  { name: "Gabriel", nicknames: ["Gabe"], origins: ["Hebrew"], meaning: "God is my strength", styles: ["classic", "biblical"], traits: ["elegant", "established"], popularityTier: "common" },
  { name: "Ezra", nicknames: [], origins: ["Hebrew"], meaning: "Help", styles: ["biblical", "vintage", "short-punchy"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Elijah", nicknames: ["Eli"], origins: ["Hebrew"], meaning: "The Lord is my God", styles: ["biblical"], traits: ["traditional", "established"], popularityTier: "very-common" },
  { name: "Josiah", nicknames: ["Joe", "Jos"], origins: ["Hebrew"], meaning: "The Lord supports", styles: ["biblical"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Levi", nicknames: [], origins: ["Hebrew"], meaning: "Joined, attached", styles: ["biblical", "short-punchy"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Caleb", nicknames: ["Cal"], origins: ["Hebrew"], meaning: "Faithful, devotion", styles: ["biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Aaron", nicknames: [], origins: ["Hebrew"], meaning: "Mountain of strength", styles: ["biblical", "classic"], traits: ["traditional"], popularityTier: "common" },
  { name: "Jonah", nicknames: [], origins: ["Hebrew"], meaning: "Dove", styles: ["biblical"], traits: ["soft"], popularityTier: "common" },
  { name: "Micah", nicknames: [], origins: ["Hebrew"], meaning: "Who is like the Lord", styles: ["biblical"], traits: ["soft"], popularityTier: "common" },
  { name: "Asher", nicknames: ["Ash"], origins: ["Hebrew"], meaning: "Happy, blessed", styles: ["biblical"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Simon", nicknames: ["Si"], origins: ["Hebrew"], meaning: "He has heard", styles: ["biblical", "classic"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Zachary", nicknames: ["Zach", "Zac", "Zack"], origins: ["Hebrew"], meaning: "The Lord remembers", styles: ["biblical", "classic"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Nathan", nicknames: ["Nate"], origins: ["Hebrew"], meaning: "He gave", styles: ["biblical", "classic"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Timothy", nicknames: ["Tim", "Timmy"], origins: ["Greek"], meaning: "Honoring God", styles: ["biblical", "classic"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Malachi", nicknames: ["Mal"], origins: ["Hebrew"], meaning: "My messenger", styles: ["biblical", "rare"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Ezekiel", nicknames: ["Zeke"], origins: ["Hebrew"], meaning: "God strengthens", styles: ["biblical"], traits: ["strong", "established"], popularityTier: "common" },

  // ===== MODERN POPULAR =====
  { name: "Liam", nicknames: [], origins: ["Irish"], meaning: "Resolute protector", styles: ["modern"], traits: ["soft", "established"], popularityTier: "very-common" },
  { name: "Mason", nicknames: [], origins: ["English"], meaning: "Stoneworker", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "very-common" },
  { name: "Logan", nicknames: [], origins: ["Scottish"], meaning: "Small hollow", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "very-common" },
  { name: "Lucas", nicknames: ["Luke", "Luc"], origins: ["Greek"], meaning: "Light-giving", styles: ["modern", "classic"], traits: ["soft", "established"], popularityTier: "very-common" },
  { name: "Ethan", nicknames: [], origins: ["Hebrew"], meaning: "Strong, firm", styles: ["modern", "biblical"], traits: ["strong", "established"], popularityTier: "very-common" },
  { name: "Owen", nicknames: [], origins: ["Welsh"], meaning: "Young warrior", styles: ["modern", "classic"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Wyatt", nicknames: [], origins: ["English"], meaning: "Brave in war", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Caleb", nicknames: ["Cal"], origins: ["Hebrew"], meaning: "Faithful, devotion", styles: ["modern", "biblical"], traits: ["traditional"], popularityTier: "common" },
  { name: "Carter", nicknames: [], origins: ["English"], meaning: "Cart driver", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Hunter", nicknames: [], origins: ["English"], meaning: "One who hunts", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Jackson", nicknames: ["Jack"], origins: ["English"], meaning: "Son of Jack", styles: ["modern", "surname-style"], traits: ["strong", "established"], popularityTier: "very-common" },
  { name: "Grayson", nicknames: ["Gray"], origins: ["English"], meaning: "Son of the steward", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Landon", nicknames: [], origins: ["English"], meaning: "Long hill", styles: ["modern", "surname-style"], traits: ["soft"], popularityTier: "common" },
  { name: "Cooper", nicknames: [], origins: ["English"], meaning: "Barrel maker", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Colton", nicknames: ["Colt"], origins: ["English"], meaning: "Coal town", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Easton", nicknames: [], origins: ["English"], meaning: "East-facing place", styles: ["modern", "surname-style"], traits: ["soft"], popularityTier: "common" },
  { name: "Bentley", nicknames: ["Ben"], origins: ["English"], meaning: "Meadow of coarse grass", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Weston", nicknames: ["West"], origins: ["English"], meaning: "Western town", styles: ["modern", "surname-style"], traits: ["soft"], popularityTier: "common" },
  { name: "Brooks", nicknames: [], origins: ["English"], meaning: "Near the stream", styles: ["modern", "surname-style", "nature"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Kai", nicknames: [], origins: ["Hawaiian"], meaning: "Sea", styles: ["modern", "short-punchy", "nature"], traits: ["soft"], popularityTier: "common" },

  // ===== TRENDY INVENTED / -AYDEN FAMILY (kept but tagged distinctly) =====
  { name: "Jaxon", nicknames: ["Jax"], origins: ["English"], meaning: "Son of Jack (respelled)", styles: ["invented", "modern"], traits: ["strong", "unusual"], popularityTier: "common" },
  { name: "Brayden", nicknames: ["Bray"], origins: ["Irish"], meaning: "Broad hill (respelled)", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "common" },
  { name: "Ryker", nicknames: ["Ry"], origins: ["Danish"], meaning: "Rich", styles: ["invented", "modern", "strong"], traits: ["unusual", "strong"], popularityTier: "common" },
  { name: "Zayden", nicknames: ["Zay"], origins: ["Invented"], meaning: "Modern coinage", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "uncommon" },
  { name: "Maverick", nicknames: ["Mav"], origins: ["English"], meaning: "Independent, nonconformist", styles: ["invented", "modern", "strong"], traits: ["unusual", "strong"], popularityTier: "common" },
  { name: "Kayden", nicknames: ["Kay"], origins: ["Invented"], meaning: "Modern coinage", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "common" },
  { name: "Aiden", nicknames: ["Aid"], origins: ["Irish"], meaning: "Little fire", styles: ["modern"], traits: ["soft", "established"], popularityTier: "very-common" },
  { name: "Grayden", nicknames: [], origins: ["Invented"], meaning: "Modern coinage", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "rare" },

  // ===== STRONG / RUGGED =====
  { name: "Axel", nicknames: [], origins: ["Scandinavian"], meaning: "Father of peace", styles: ["strong", "modern"], traits: ["strong"], popularityTier: "common" },
  { name: "Bear", nicknames: [], origins: ["English"], meaning: "Bear", styles: ["strong", "nature", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Blaze", nicknames: [], origins: ["English"], meaning: "Fire", styles: ["strong", "invented"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Rex", nicknames: [], origins: ["Latin"], meaning: "King", styles: ["strong", "short-punchy", "vintage"], traits: ["strong"], popularityTier: "rare" },
  { name: "Duke", nicknames: [], origins: ["English"], meaning: "Leader", styles: ["strong", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Knox", nicknames: [], origins: ["Scottish"], meaning: "Round hill", styles: ["strong", "surname-style", "short-punchy"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Ranger", nicknames: [], origins: ["English"], meaning: "Forest guardian", styles: ["strong", "nature", "invented"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Titan", nicknames: [], origins: ["Greek"], meaning: "Giant", styles: ["strong", "rare"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Steel", nicknames: [], origins: ["English"], meaning: "Steel", styles: ["strong", "invented"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Wolf", nicknames: [], origins: ["German"], meaning: "Wolf", styles: ["strong", "nature", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Bronson", nicknames: ["Bron"], origins: ["English"], meaning: "Son of the brown-haired one", styles: ["strong", "surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Sawyer", nicknames: [], origins: ["English"], meaning: "Woodcutter", styles: ["strong", "surname-style", "literary"], traits: ["strong"], popularityTier: "common" },
  { name: "Gunner", nicknames: ["Gunn"], origins: ["Scandinavian"], meaning: "Bold warrior", styles: ["strong", "modern"], traits: ["strong"], popularityTier: "common" },
  { name: "Rhodes", nicknames: [], origins: ["Greek"], meaning: "Where roses grow", styles: ["strong", "surname-style"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Sterling", nicknames: ["Stern"], origins: ["English"], meaning: "Of high quality", styles: ["strong", "surname-style"], traits: ["strong"], popularityTier: "uncommon" },

  // ===== SOFT / GENTLE =====
  { name: "Milo", nicknames: [], origins: ["German"], meaning: "Soldier, merciful", styles: ["soft", "vintage", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "common" },
  { name: "Leo", nicknames: [], origins: ["Latin"], meaning: "Lion", styles: ["soft", "classic", "short-punchy"], traits: ["soft", "established"], popularityTier: "very-common" },
  { name: "Felix", nicknames: [], origins: ["Latin"], meaning: "Happy, fortunate", styles: ["soft", "vintage"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Hugo", nicknames: [], origins: ["German"], meaning: "Mind, intellect", styles: ["soft", "international", "vintage"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Otto", nicknames: [], origins: ["German"], meaning: "Wealth, prosperity", styles: ["soft", "vintage", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Wren", nicknames: [], origins: ["English"], meaning: "Small bird", styles: ["soft", "nature", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Fox", nicknames: [], origins: ["English"], meaning: "Fox", styles: ["soft", "nature", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Remy", nicknames: [], origins: ["French"], meaning: "Oarsman", styles: ["soft", "international", "short-punchy"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Finn", nicknames: [], origins: ["Irish"], meaning: "Fair, white", styles: ["soft", "short-punchy"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Miles", nicknames: [], origins: ["Latin"], meaning: "Soldier", styles: ["soft", "classic"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Jasper", nicknames: ["Jas"], origins: ["Persian"], meaning: "Treasurer", styles: ["soft", "vintage"], traits: ["soft"], popularityTier: "common" },
  { name: "Rhys", nicknames: [], origins: ["Welsh"], meaning: "Ardor, enthusiasm", styles: ["soft", "international", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Sage", nicknames: [], origins: ["English"], meaning: "Wise one", styles: ["soft", "nature", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Bodhi", nicknames: [], origins: ["Sanskrit"], meaning: "Awakening", styles: ["soft", "rare", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Ellis", nicknames: [], origins: ["Welsh"], meaning: "Benevolent", styles: ["soft", "surname-style"], traits: ["soft"], popularityTier: "uncommon" },

  // ===== NATURE =====
  { name: "River", nicknames: [], origins: ["English"], meaning: "Flowing water", styles: ["nature", "modern"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Forest", nicknames: ["Forrest"], origins: ["English"], meaning: "Woodland", styles: ["nature"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Cedar", nicknames: [], origins: ["English"], meaning: "Cedar tree", styles: ["nature", "rare"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Stone", nicknames: [], origins: ["English"], meaning: "Stone", styles: ["nature", "strong", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Reed", nicknames: [], origins: ["English"], meaning: "Red-haired, reed", styles: ["nature", "short-punchy"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Orion", nicknames: [], origins: ["Greek"], meaning: "The hunter, constellation", styles: ["nature", "rare", "strong"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Storm", nicknames: [], origins: ["English"], meaning: "Tempest", styles: ["nature", "strong"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Falcon", nicknames: [], origins: ["English"], meaning: "Falcon", styles: ["nature", "strong"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Hawk", nicknames: [], origins: ["English"], meaning: "Hawk", styles: ["nature", "strong", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Wilder", nicknames: [], origins: ["English"], meaning: "Wild, untamed", styles: ["nature", "modern"], traits: ["strong", "unusual"], popularityTier: "uncommon" },

  // ===== INTERNATIONAL =====
  { name: "Matteo", nicknames: ["Teo"], origins: ["Italian"], meaning: "Gift of God", styles: ["international"], traits: ["elegant"], popularityTier: "common" },
  { name: "Luca", nicknames: [], origins: ["Italian"], meaning: "Man from Lucania", styles: ["international", "short-punchy"], traits: ["elegant", "soft"], popularityTier: "common" },
  { name: "Enzo", nicknames: [], origins: ["Italian"], meaning: "Ruler of the home", styles: ["international", "short-punchy"], traits: ["elegant"], popularityTier: "common" },
  { name: "Diego", nicknames: [], origins: ["Spanish"], meaning: "Supplanter", styles: ["international"], traits: ["elegant"], popularityTier: "common" },
  { name: "Mateo", nicknames: [], origins: ["Spanish"], meaning: "Gift of God", styles: ["international"], traits: ["elegant"], popularityTier: "very-common" },
  { name: "Santiago", nicknames: ["Santi", "Iago"], origins: ["Spanish"], meaning: "Saint James", styles: ["international"], traits: ["elegant"], popularityTier: "common" },
  { name: "Emiliano", nicknames: ["Emi"], origins: ["Italian", "Spanish"], meaning: "Rival", styles: ["international"], traits: ["elegant"], popularityTier: "uncommon" },
  { name: "Lorenzo", nicknames: ["Enzo", "Renzo"], origins: ["Italian"], meaning: "From Laurentum", styles: ["international", "classic"], traits: ["elegant"], popularityTier: "common" },
  { name: "Rafael", nicknames: ["Rafa"], origins: ["Hebrew", "Spanish"], meaning: "God has healed", styles: ["international", "biblical"], traits: ["elegant"], popularityTier: "common" },
  { name: "Emil", nicknames: [], origins: ["German", "Scandinavian"], meaning: "Rival, eager", styles: ["international", "vintage"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Anders", nicknames: [], origins: ["Scandinavian"], meaning: "Manly, brave", styles: ["international"], traits: ["strong"], popularityTier: "rare" },
  { name: "Felix", nicknames: [], origins: ["German", "Latin"], meaning: "Happy, fortunate", styles: ["international", "vintage"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Kai", nicknames: [], origins: ["Welsh", "Hawaiian"], meaning: "Sea, keeper of the keys", styles: ["international", "short-punchy"], traits: ["soft"], popularityTier: "common" },
  { name: "Aksel", nicknames: [], origins: ["Scandinavian"], meaning: "Father of peace", styles: ["international", "strong"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Niko", nicknames: [], origins: ["Greek"], meaning: "Victory of the people", styles: ["international", "short-punchy"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Dimitri", nicknames: ["Mitri"], origins: ["Russian", "Greek"], meaning: "Follower of Demeter", styles: ["international"], traits: ["elegant", "strong"], popularityTier: "uncommon" },
  { name: "Amos", nicknames: [], origins: ["Hebrew"], meaning: "Carried by God", styles: ["biblical", "vintage", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Kofi", nicknames: [], origins: ["Akan/Ghanaian"], meaning: "Born on Friday", styles: ["international", "rare"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Kenji", nicknames: [], origins: ["Japanese"], meaning: "Intelligent second son", styles: ["international"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Idris", nicknames: [], origins: ["Welsh", "Arabic"], meaning: "Ardent lord, interpreter", styles: ["international", "rare"], traits: ["elegant", "unusual"], popularityTier: "uncommon" },
  { name: "Amir", nicknames: [], origins: ["Arabic"], meaning: "Prince, commander", styles: ["international"], traits: ["strong", "elegant"], popularityTier: "uncommon" },
  { name: "Omar", nicknames: [], origins: ["Arabic"], meaning: "Flourishing, long-lived", styles: ["international"], traits: ["strong"], popularityTier: "common" },
  { name: "Rio", nicknames: [], origins: ["Spanish"], meaning: "River", styles: ["international", "short-punchy", "nature"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Aarav", nicknames: [], origins: ["Sanskrit"], meaning: "Peaceful", styles: ["international"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Arjun", nicknames: [], origins: ["Sanskrit"], meaning: "Bright, shining", styles: ["international"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Kian", nicknames: [], origins: ["Persian", "Irish"], meaning: "King, ancient", styles: ["international", "modern"], traits: ["strong"], popularityTier: "common" },
  { name: "Zion", nicknames: [], origins: ["Hebrew"], meaning: "Highest point, promised land", styles: ["biblical", "modern"], traits: ["strong", "unusual"], popularityTier: "common" },
  { name: "Elio", nicknames: [], origins: ["Italian"], meaning: "The sun", styles: ["international", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Pablo", nicknames: [], origins: ["Spanish"], meaning: "Small", styles: ["international"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Andre", nicknames: ["Dre"], origins: ["French"], meaning: "Manly, brave", styles: ["international", "classic"], traits: ["strong"], popularityTier: "common" },

  // ===== SHORT & PUNCHY =====
  { name: "Jack", nicknames: [], origins: ["English"], meaning: "God is gracious", styles: ["short-punchy", "classic"], traits: ["strong", "established"], popularityTier: "very-common" },
  { name: "Max", nicknames: [], origins: ["Latin"], meaning: "Greatest", styles: ["short-punchy", "classic"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Cole", nicknames: [], origins: ["English"], meaning: "Charcoal, dark", styles: ["short-punchy", "modern"], traits: ["strong"], popularityTier: "common" },
  { name: "Beau", nicknames: [], origins: ["French"], meaning: "Handsome", styles: ["short-punchy", "soft"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Jude", nicknames: [], origins: ["Hebrew"], meaning: "Praised", styles: ["short-punchy", "biblical"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Gus", nicknames: [], origins: ["Latin"], meaning: "Great, magnificent", styles: ["short-punchy", "vintage"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Ray", nicknames: [], origins: ["French"], meaning: "Counsel, protection", styles: ["short-punchy", "vintage"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Zane", nicknames: [], origins: ["Hebrew"], meaning: "God is gracious", styles: ["short-punchy", "modern"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Nash", nicknames: [], origins: ["English"], meaning: "By the ash tree", styles: ["short-punchy", "surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Grant", nicknames: [], origins: ["English"], meaning: "Great, large", styles: ["short-punchy", "classic"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Chase", nicknames: [], origins: ["English"], meaning: "Hunter", styles: ["short-punchy", "modern"], traits: ["strong"], popularityTier: "common" },
  { name: "Dean", nicknames: [], origins: ["English"], meaning: "Valley", styles: ["short-punchy", "vintage"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Shane", nicknames: [], origins: ["Irish"], meaning: "God is gracious", styles: ["short-punchy"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Kent", nicknames: [], origins: ["English"], meaning: "Edge, border", styles: ["short-punchy", "surname-style"], traits: ["strong"], popularityTier: "rare" },
  { name: "Lane", nicknames: [], origins: ["English"], meaning: "Path, roadway", styles: ["short-punchy", "surname-style"], traits: ["soft"], popularityTier: "uncommon" },

  // ===== SURNAME-STYLE =====
  { name: "Emerson", nicknames: ["Emery"], origins: ["English"], meaning: "Son of Emery", styles: ["surname-style", "literary"], traits: ["soft"], popularityTier: "common" },
  { name: "Anderson", nicknames: ["Andy"], origins: ["English"], meaning: "Son of Andrew", styles: ["surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Harrison", nicknames: ["Harry"], origins: ["English"], meaning: "Son of Harry", styles: ["surname-style", "classic"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Bennett", nicknames: ["Ben"], origins: ["English"], meaning: "Blessed", styles: ["surname-style", "classic"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Beckett", nicknames: ["Beck"], origins: ["English"], meaning: "Bee cottage", styles: ["surname-style", "literary"], traits: ["soft", "unusual"], popularityTier: "common" },
  { name: "Sullivan", nicknames: ["Sully"], origins: ["Irish"], meaning: "Dark-eyed", styles: ["surname-style"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Sutton", nicknames: [], origins: ["English"], meaning: "Southern town", styles: ["surname-style"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Tanner", nicknames: [], origins: ["English"], meaning: "Leather worker", styles: ["surname-style", "modern"], traits: ["strong"], popularityTier: "common" },
  { name: "Parker", nicknames: [], origins: ["English"], meaning: "Park keeper", styles: ["surname-style", "modern"], traits: ["soft"], popularityTier: "common" },
  { name: "Spencer", nicknames: ["Spence"], origins: ["English"], meaning: "Steward, dispenser", styles: ["surname-style", "classic"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Preston", nicknames: [], origins: ["English"], meaning: "Priest's town", styles: ["surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Holden", nicknames: [], origins: ["English"], meaning: "Deep valley", styles: ["surname-style", "literary"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Barrett", nicknames: [], origins: ["German"], meaning: "Strong as a bear", styles: ["surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Crosby", nicknames: [], origins: ["Scandinavian"], meaning: "Village with crosses", styles: ["surname-style"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Whitman", nicknames: ["Whit"], origins: ["English"], meaning: "White-headed man", styles: ["surname-style", "literary"], traits: ["soft", "unusual"], popularityTier: "rare" },

  // ===== RARE / UNIQUE =====
  { name: "Atticus", nicknames: [], origins: ["Greek"], meaning: "Man of Attica", styles: ["rare", "literary"], traits: ["elegant", "unusual"], popularityTier: "uncommon" },
  { name: "Ignatius", nicknames: ["Iggy", "Nate"], origins: ["Latin"], meaning: "Fiery one", styles: ["rare", "vintage"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Barnaby", nicknames: ["Barney"], origins: ["Hebrew"], meaning: "Son of encouragement", styles: ["rare", "vintage"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Peregrine", nicknames: ["Perry"], origins: ["Latin"], meaning: "Traveler, wanderer", styles: ["rare", "vintage"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Thaddeus", nicknames: ["Thad", "Teddy"], origins: ["Aramaic"], meaning: "Courageous heart", styles: ["rare", "biblical"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Cornelius", nicknames: ["Neil", "Cory"], origins: ["Latin"], meaning: "Horn", styles: ["rare", "vintage"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Percival", nicknames: ["Percy"], origins: ["French"], meaning: "Pierce the valley", styles: ["rare", "literary"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Montgomery", nicknames: ["Monty"], origins: ["French"], meaning: "Mountain of the ruler", styles: ["rare", "surname-style"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Octavian", nicknames: ["Tavi"], origins: ["Latin"], meaning: "Eighth", styles: ["rare", "vintage"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Alaric", nicknames: [], origins: ["German"], meaning: "Ruler of all", styles: ["rare", "strong"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Casimir", nicknames: ["Caz", "Kazik"], origins: ["Polish"], meaning: "Proclaims peace", styles: ["rare", "international"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Leopold", nicknames: ["Leo", "Leopoldo"], origins: ["German"], meaning: "Bold people", styles: ["rare", "vintage"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Balthazar", nicknames: ["Baz"], origins: ["Babylonian"], meaning: "Protect the king", styles: ["rare", "biblical"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Ambrose", nicknames: ["Bram"], origins: ["Greek"], meaning: "Immortal", styles: ["rare", "vintage"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Caspian", nicknames: ["Cas"], origins: ["Literary"], meaning: "From the Caspian Sea", styles: ["rare", "literary"], traits: ["elegant", "unusual"], popularityTier: "uncommon" },

  // ===== LITERARY =====
  { name: "Atlas", nicknames: [], origins: ["Greek"], meaning: "Enduring, bearer of the heavens", styles: ["literary", "strong", "rare"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Dashiell", nicknames: ["Dash"], origins: ["French"], meaning: "Page boy", styles: ["literary", "rare"], traits: ["elegant", "unusual"], popularityTier: "rare" },
  { name: "Gatsby", nicknames: [], origins: ["Literary"], meaning: "Literary namesake", styles: ["literary", "rare", "invented"], traits: ["unusual"], popularityTier: "rare" },
  { name: "Huxley", nicknames: ["Hux"], origins: ["English"], meaning: "Inhospitable place", styles: ["literary", "surname-style"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Fitzgerald", nicknames: ["Fitz"], origins: ["Irish"], meaning: "Son of Gerald", styles: ["literary", "surname-style", "rare"], traits: ["unusual"], popularityTier: "rare" },
  { name: "Darcy", nicknames: [], origins: ["French"], meaning: "From Arcy", styles: ["literary", "surname-style"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Heathcliff", nicknames: ["Heath"], origins: ["English"], meaning: "Cliff near the heath", styles: ["literary", "rare"], traits: ["strong", "unusual"], popularityTier: "rare" },
  { name: "Sherlock", nicknames: [], origins: ["English"], meaning: "Bright hair", styles: ["literary", "rare"], traits: ["unusual"], popularityTier: "rare" },
  { name: "Wilde", nicknames: [], origins: ["English"], meaning: "Wild", styles: ["literary", "rare", "short-punchy"], traits: ["unusual"], popularityTier: "rare" },
  { name: "Aldous", nicknames: [], origins: ["German"], meaning: "Old, wise", styles: ["literary", "rare"], traits: ["elegant", "unusual"], popularityTier: "rare" },

  // ===== ADDITIONAL CLASSIC & POPULAR (rounding out breadth) =====
  { name: "Christopher", nicknames: ["Chris", "Topher", "Kit"], origins: ["Greek"], meaning: "Bearer of Christ", styles: ["classic"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Anthony", nicknames: ["Tony", "Ant"], origins: ["Latin"], meaning: "Priceless one", styles: ["classic"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Nicholas", nicknames: ["Nick", "Nico"], origins: ["Greek"], meaning: "Victory of the people", styles: ["classic"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Patrick", nicknames: ["Pat", "Paddy"], origins: ["Latin"], meaning: "Nobleman", styles: ["classic"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Sean", nicknames: ["Shawn"], origins: ["Irish"], meaning: "God is gracious", styles: ["classic"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Ryan", nicknames: [], origins: ["Irish"], meaning: "Little king", styles: ["classic", "modern"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Brandon", nicknames: ["Bran"], origins: ["English"], meaning: "Broom-covered hill", styles: ["classic", "modern"], traits: ["soft"], popularityTier: "common" },
  { name: "Justin", nicknames: [], origins: ["Latin"], meaning: "Just, righteous", styles: ["classic", "modern"], traits: ["soft"], popularityTier: "common" },
  { name: "Vincent", nicknames: ["Vince", "Vinny"], origins: ["Latin"], meaning: "Conquering", styles: ["classic", "vintage"], traits: ["elegant"], popularityTier: "common" },
  { name: "Marcus", nicknames: ["Marc"], origins: ["Latin"], meaning: "Dedicated to Mars", styles: ["classic", "strong"], traits: ["strong"], popularityTier: "common" },
  { name: "Victor", nicknames: ["Vic"], origins: ["Latin"], meaning: "Conqueror", styles: ["classic", "strong"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Leonard", nicknames: ["Leo", "Len"], origins: ["German"], meaning: "Brave lion", styles: ["vintage", "classic"], traits: ["traditional", "soft"], popularityTier: "rare" },
  { name: "Raymond", nicknames: ["Ray"], origins: ["German"], meaning: "Wise protector", styles: ["vintage", "classic"], traits: ["traditional"], popularityTier: "rare" },
  { name: "Bernard", nicknames: ["Bernie"], origins: ["German"], meaning: "Brave as a bear", styles: ["vintage"], traits: ["traditional"], popularityTier: "rare" },
  { name: "Herbert", nicknames: ["Herb", "Bertie"], origins: ["German"], meaning: "Glorious army", styles: ["vintage"], traits: ["traditional", "rare"], popularityTier: "rare" },
  { name: "Clarence", nicknames: ["Clare"], origins: ["Latin"], meaning: "Clear, bright", styles: ["vintage"], traits: ["traditional", "rare"], popularityTier: "rare" },
  { name: "Eugene", nicknames: ["Gene"], origins: ["Greek"], meaning: "Well-born", styles: ["vintage"], traits: ["traditional", "rare"], popularityTier: "rare" },
  { name: "Harold", nicknames: ["Harry", "Hal"], origins: ["English"], meaning: "Army ruler", styles: ["vintage"], traits: ["traditional", "rare"], popularityTier: "rare" },
  { name: "Norman", nicknames: ["Norm"], origins: ["German"], meaning: "Northman", styles: ["vintage"], traits: ["traditional", "rare"], popularityTier: "rare" },
  { name: "Stanley", nicknames: ["Stan"], origins: ["English"], meaning: "Stony meadow", styles: ["vintage"], traits: ["traditional", "soft"], popularityTier: "uncommon" },
  { name: "Elliott", nicknames: ["Eli", "El"], origins: ["Hebrew"], meaning: "The Lord is my God", styles: ["classic", "literary"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Graham", nicknames: [], origins: ["English"], meaning: "Gravel homestead", styles: ["classic", "surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Colin", nicknames: [], origins: ["Irish"], meaning: "Young cub", styles: ["classic"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Bruce", nicknames: [], origins: ["Scottish"], meaning: "From the brushwood thicket", styles: ["vintage", "strong"], traits: ["strong"], popularityTier: "rare" },
  { name: "Neil", nicknames: [], origins: ["Irish"], meaning: "Champion", styles: ["classic", "short-punchy"], traits: ["strong"], popularityTier: "rare" },
  { name: "Craig", nicknames: [], origins: ["Scottish"], meaning: "Rock, crag", styles: ["classic", "short-punchy"], traits: ["strong"], popularityTier: "rare" },
  { name: "Douglas", nicknames: ["Doug"], origins: ["Scottish"], meaning: "Dark river", styles: ["vintage", "surname-style"], traits: ["strong"], popularityTier: "rare" },
  { name: "Gordon", nicknames: ["Gordie"], origins: ["Scottish"], meaning: "Great hill", styles: ["vintage", "surname-style"], traits: ["strong"], popularityTier: "rare" },
  { name: "Lewis", nicknames: ["Lew"], origins: ["Welsh"], meaning: "Renowned warrior", styles: ["classic"], traits: ["strong", "traditional"], popularityTier: "uncommon" },
  { name: "Marshall", nicknames: ["Marsh"], origins: ["French"], meaning: "Steward, caretaker of horses", styles: ["surname-style", "strong"], traits: ["strong"], popularityTier: "uncommon" },

  // ===== MORE INVENTED / MODERN TRENDY =====
  { name: "Legend", nicknames: [], origins: ["English"], meaning: "Legendary", styles: ["invented", "modern"], traits: ["unusual", "strong"], popularityTier: "uncommon" },
  { name: "Phoenix", nicknames: [], origins: ["Greek"], meaning: "Mythical firebird", styles: ["invented", "modern", "nature"], traits: ["unusual", "strong"], popularityTier: "common" },
  { name: "Kingston", nicknames: ["King"], origins: ["English"], meaning: "King's town", styles: ["invented", "modern", "surname-style"], traits: ["unusual", "strong"], popularityTier: "common" },
  { name: "Bodie", nicknames: [], origins: ["English"], meaning: "Dweller near a channel", styles: ["invented", "modern", "short-punchy"], traits: ["unusual"], popularityTier: "uncommon" },
  { name: "Cash", nicknames: [], origins: ["English"], meaning: "Wealthy", styles: ["invented", "modern", "short-punchy"], traits: ["unusual", "strong"], popularityTier: "common" },
  { name: "Rowdy", nicknames: [], origins: ["English"], meaning: "Rowdy, boisterous", styles: ["invented", "modern"], traits: ["unusual", "strong"], popularityTier: "rare" },
  { name: "Justice", nicknames: [], origins: ["English"], meaning: "Justice", styles: ["invented", "modern"], traits: ["unusual", "strong"], popularityTier: "uncommon" },
  { name: "Remington", nicknames: ["Remy"], origins: ["English"], meaning: "Raven settlement", styles: ["invented", "modern", "surname-style"], traits: ["unusual", "strong"], popularityTier: "uncommon" },
  { name: "Ace", nicknames: [], origins: ["Latin"], meaning: "Unity, one", styles: ["invented", "modern", "short-punchy"], traits: ["unusual", "strong"], popularityTier: "uncommon" },
  { name: "Zeke", nicknames: [], origins: ["Hebrew"], meaning: "God strengthens", styles: ["invented", "short-punchy"], traits: ["unusual", "strong"], popularityTier: "common" },

  // ===== MORE BIBLICAL/CLASSIC DEPTH =====
  { name: "Amos", nicknames: [], origins: ["Hebrew"], meaning: "Carried by God", styles: ["biblical", "vintage"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Reuben", nicknames: ["Ben", "Rube"], origins: ["Hebrew"], meaning: "Behold, a son", styles: ["biblical", "vintage"], traits: ["traditional", "unusual"], popularityTier: "rare" },
  { name: "Solomon", nicknames: ["Sol", "Solly"], origins: ["Hebrew"], meaning: "Peace", styles: ["biblical", "classic"], traits: ["traditional", "established"], popularityTier: "uncommon" },
  { name: "Abel", nicknames: [], origins: ["Hebrew"], meaning: "Breath", styles: ["biblical", "short-punchy"], traits: ["soft"], popularityTier: "common" },
  { name: "Elisha", nicknames: ["Eli"], origins: ["Hebrew"], meaning: "God is salvation", styles: ["biblical"], traits: ["soft", "unusual"], popularityTier: "rare" },
  { name: "Jeremiah", nicknames: ["Jerry", "Remy"], origins: ["Hebrew"], meaning: "God will exalt", styles: ["biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Isaiah", nicknames: ["Zay"], origins: ["Hebrew"], meaning: "God is salvation", styles: ["biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Emmanuel", nicknames: ["Manny"], origins: ["Hebrew"], meaning: "God is with us", styles: ["biblical"], traits: ["traditional", "elegant"], popularityTier: "uncommon" },
  { name: "Judah", nicknames: ["Jude"], origins: ["Hebrew"], meaning: "Praised", styles: ["biblical"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Enoch", nicknames: [], origins: ["Hebrew"], meaning: "Dedicated, trained", styles: ["biblical", "rare"], traits: ["soft", "unusual"], popularityTier: "rare" },

  // ===== ADDED FROM REAL SSA TOP-300 DATA (2007-2016 aggregate, USA) =====
  // These fill gaps between our curated set and the actual top 300 most-registered
  // boy names. popularityTier below is a placeholder — computed for real from
  // SSA rank further down in this script, overriding every entry's guess.
  { name: "Jayden", nicknames: ["Jay"], origins: ["American (invented)"], meaning: "Thankful", styles: ["invented", "modern"], traits: ["unusual", "established"], popularityTier: "common" },
  { name: "Joshua", nicknames: ["Josh"], origins: ["Hebrew"], meaning: "The Lord is salvation", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "John", nicknames: ["Johnny", "Jack"], origins: ["Hebrew"], meaning: "God is gracious", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Dylan", nicknames: ["Dyl"], origins: ["Welsh"], meaning: "Son of the sea", styles: ["modern", "literary"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Christian", nicknames: ["Chris"], origins: ["Latin"], meaning: "Follower of Christ", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Jonathan", nicknames: ["Jon", "Jonny", "Nathan"], origins: ["Hebrew"], meaning: "Gift of God", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Luke", nicknames: ["Luc"], origins: ["Greek"], meaning: "Light-giving", styles: ["classic", "biblical", "short-punchy"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Tyler", nicknames: ["Ty"], origins: ["English"], meaning: "Tile maker", styles: ["modern", "surname-style"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Gavin", nicknames: ["Gav"], origins: ["Welsh"], meaning: "White hawk", styles: ["modern", "classic"], traits: ["soft"], popularityTier: "common" },
  { name: "Evan", nicknames: ["Ev"], origins: ["Welsh"], meaning: "Young warrior", styles: ["modern", "classic"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Angel", nicknames: [], origins: ["Greek"], meaning: "Messenger of God", styles: ["international", "biblical", "soft"], traits: ["soft", "elegant"], popularityTier: "common" },
  { name: "Jordan", nicknames: ["Jordy"], origins: ["Hebrew"], meaning: "To flow down", styles: ["modern", "surname-style"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Connor", nicknames: ["Con"], origins: ["Irish"], meaning: "Lover of hounds", styles: ["modern", "surname-style"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Cameron", nicknames: ["Cam"], origins: ["Scottish"], meaning: "Crooked nose", styles: ["modern", "surname-style"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Jose", nicknames: ["Pepe"], origins: ["Spanish"], meaning: "God will increase", styles: ["international", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Kevin", nicknames: ["Kev"], origins: ["Irish"], meaning: "Handsome, beloved", styles: ["classic", "modern"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Austin", nicknames: [], origins: ["English"], meaning: "Great, magnificent", styles: ["modern", "surname-style"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Eli", nicknames: [], origins: ["Hebrew"], meaning: "Ascended", styles: ["biblical", "short-punchy"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Jason", nicknames: ["Jace"], origins: ["Greek"], meaning: "Healer", styles: ["classic"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Dominic", nicknames: ["Dom", "Nico"], origins: ["Latin"], meaning: "Belonging to the Lord", styles: ["classic", "biblical"], traits: ["strong"], popularityTier: "common" },
  { name: "Ian", nicknames: [], origins: ["Scottish"], meaning: "God is gracious", styles: ["classic", "short-punchy"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Adam", nicknames: [], origins: ["Hebrew"], meaning: "Man, earth", styles: ["classic", "biblical", "short-punchy"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Xavier", nicknames: ["Xave"], origins: ["Basque"], meaning: "New house, bright", styles: ["modern", "international"], traits: ["strong", "unusual"], popularityTier: "common" },
  { name: "Ayden", nicknames: ["Ay"], origins: ["American (respelled)"], meaning: "Little fire", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "common" },
  { name: "Luis", nicknames: [], origins: ["Spanish"], meaning: "Renowned warrior", styles: ["international", "classic"], traits: ["strong"], popularityTier: "common" },
  { name: "Blake", nicknames: [], origins: ["English"], meaning: "Fair-haired, dark", styles: ["modern", "surname-style", "short-punchy"], traits: ["strong"], popularityTier: "common" },
  { name: "Juan", nicknames: [], origins: ["Spanish"], meaning: "God is gracious", styles: ["international", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Carson", nicknames: [], origins: ["Scottish"], meaning: "Son of the marsh-dwellers", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Brody", nicknames: [], origins: ["Irish"], meaning: "Ditch, muddy place", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Tristan", nicknames: ["Tris"], origins: ["Celtic"], meaning: "Tumult, noise", styles: ["classic", "literary"], traits: ["elegant"], popularityTier: "common" },
  { name: "Carlos", nicknames: [], origins: ["Spanish"], meaning: "Free man", styles: ["international", "classic"], traits: ["strong"], popularityTier: "common" },
  { name: "Nolan", nicknames: [], origins: ["Irish"], meaning: "Champion, noble", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Jesus", nicknames: ["Chuy"], origins: ["Hebrew", "Spanish"], meaning: "God is salvation", styles: ["biblical", "international"], traits: ["traditional"], popularityTier: "common" },
  { name: "Aidan", nicknames: ["Aid"], origins: ["Irish"], meaning: "Little fire", styles: ["modern"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Alex", nicknames: [], origins: ["Greek"], meaning: "Defender of the people", styles: ["classic", "short-punchy"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Jace", nicknames: [], origins: ["American (invented)"], meaning: "Healer", styles: ["invented", "modern", "short-punchy"], traits: ["unusual"], popularityTier: "common" },
  { name: "Hayden", nicknames: ["Hay"], origins: ["English"], meaning: "Hedged valley", styles: ["modern", "surname-style"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Eric", nicknames: ["Rick"], origins: ["Scandinavian"], meaning: "Eternal ruler", styles: ["classic"], traits: ["strong"], popularityTier: "common" },
  { name: "Hudson", nicknames: ["Hud"], origins: ["English"], meaning: "Son of Hugh", styles: ["modern", "surname-style", "nature"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Bryan", nicknames: ["Bry"], origins: ["Irish"], meaning: "Noble, strong", styles: ["classic"], traits: ["strong"], popularityTier: "common" },
  { name: "Jaden", nicknames: ["Jay"], origins: ["American (invented)"], meaning: "Thankful", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "common" },
  { name: "Brian", nicknames: ["Bry"], origins: ["Irish"], meaning: "Noble, strong", styles: ["classic"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Lincoln", nicknames: ["Linc"], origins: ["English"], meaning: "Lake colony", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Damian", nicknames: ["Dame"], origins: ["Greek"], meaning: "To tame, subdue", styles: ["classic", "strong"], traits: ["strong", "unusual"], popularityTier: "common" },
  { name: "Antonio", nicknames: ["Tony"], origins: ["Latin"], meaning: "Priceless one", styles: ["classic", "international"], traits: ["elegant"], popularityTier: "common" },
  { name: "Miguel", nicknames: ["Mike"], origins: ["Spanish"], meaning: "Who is like God", styles: ["international", "biblical"], traits: ["elegant"], popularityTier: "common" },
  { name: "Bryce", nicknames: [], origins: ["Scottish"], meaning: "Speckled, freckled", styles: ["modern", "short-punchy"], traits: ["strong"], popularityTier: "common" },
  { name: "Kyle", nicknames: [], origins: ["Scottish"], meaning: "Narrow strait", styles: ["classic", "short-punchy"], traits: ["soft"], popularityTier: "common" },
  { name: "Steven", nicknames: ["Steve", "Stevie"], origins: ["Greek"], meaning: "Crown", styles: ["classic"], traits: ["traditional"], popularityTier: "common" },
  { name: "Bryson", nicknames: ["Bry"], origins: ["English"], meaning: "Son of Brice", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Ryder", nicknames: [], origins: ["English"], meaning: "Mounted warrior", styles: ["modern", "strong"], traits: ["strong", "unusual"], popularityTier: "common" },
  { name: "Maxwell", nicknames: ["Max"], origins: ["Scottish"], meaning: "Great stream", styles: ["classic", "surname-style"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Kaden", nicknames: ["Kade"], origins: ["American (invented)"], meaning: "Companion, fighter", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "common" },
  { name: "Jaxson", nicknames: ["Jax"], origins: ["English"], meaning: "Son of Jack", styles: ["invented", "modern"], traits: ["strong", "unusual"], popularityTier: "common" },
  { name: "Ashton", nicknames: ["Ash"], origins: ["English"], meaning: "Ash tree town", styles: ["modern", "surname-style", "nature"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Kaleb", nicknames: ["Cal"], origins: ["Hebrew"], meaning: "Faithful, devotion", styles: ["biblical", "modern"], traits: ["traditional"], popularityTier: "common" },
  { name: "Caden", nicknames: ["Cade"], origins: ["American (invented)"], meaning: "Fighter, companion", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "common" },
  { name: "Giovanni", nicknames: ["Gio"], origins: ["Italian"], meaning: "God is gracious", styles: ["international", "classic"], traits: ["elegant"], popularityTier: "common" },
  { name: "Alejandro", nicknames: ["Alex", "Ale"], origins: ["Spanish"], meaning: "Defender of the people", styles: ["international", "classic"], traits: ["elegant", "strong"], popularityTier: "common" },
  { name: "Brady", nicknames: [], origins: ["Irish"], meaning: "Spirited, broad", styles: ["modern", "surname-style"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Riley", nicknames: [], origins: ["Irish"], meaning: "Valiant, courageous", styles: ["modern", "surname-style"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Ivan", nicknames: ["Van"], origins: ["Russian"], meaning: "God is gracious", styles: ["international", "classic"], traits: ["strong"], popularityTier: "common" },
  { name: "Jesse", nicknames: [], origins: ["Hebrew"], meaning: "Gift, God exists", styles: ["classic", "biblical"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Joel", nicknames: [], origins: ["Hebrew"], meaning: "The Lord is God", styles: ["classic", "biblical", "short-punchy"], traits: ["traditional"], popularityTier: "common" },
  { name: "Leonardo", nicknames: ["Leo"], origins: ["Italian"], meaning: "Brave lion", styles: ["international", "vintage"], traits: ["elegant", "established"], popularityTier: "common" },
  { name: "Jake", nicknames: [], origins: ["Hebrew"], meaning: "Supplanter", styles: ["classic", "short-punchy"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Camden", nicknames: ["Cam"], origins: ["Scottish"], meaning: "Winding valley", styles: ["modern", "surname-style"], traits: ["soft"], popularityTier: "common" },
  { name: "Jeremy", nicknames: ["Jer"], origins: ["Hebrew"], meaning: "God will exalt", styles: ["classic", "biblical"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Braxton", nicknames: ["Brax"], origins: ["English"], meaning: "Brock's town", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Oscar", nicknames: ["Oz"], origins: ["Irish"], meaning: "Divine spear", styles: ["vintage", "classic"], traits: ["soft", "unusual"], popularityTier: "common" },
  { name: "Wesley", nicknames: ["Wes"], origins: ["English"], meaning: "Western meadow", styles: ["classic", "surname-style"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Alan", nicknames: ["Al"], origins: ["Celtic"], meaning: "Handsome, cheerful", styles: ["classic"], traits: ["traditional"], popularityTier: "common" },
  { name: "Kaiden", nicknames: ["Kai"], origins: ["American (respelled)"], meaning: "Companion, fighter", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "common" },
  { name: "Devin", nicknames: ["Dev"], origins: ["Irish"], meaning: "Poet", styles: ["modern", "surname-style"], traits: ["soft"], popularityTier: "common" },
  { name: "Mark", nicknames: [], origins: ["Latin"], meaning: "Dedicated to Mars", styles: ["classic", "short-punchy"], traits: ["traditional"], popularityTier: "common" },
  { name: "Kenneth", nicknames: ["Ken", "Kenny"], origins: ["Scottish"], meaning: "Handsome, born of fire", styles: ["classic", "vintage"], traits: ["traditional"], popularityTier: "common" },
  { name: "Cody", nicknames: [], origins: ["Irish"], meaning: "Helpful", styles: ["modern", "short-punchy"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Nicolas", nicknames: ["Nico", "Nick"], origins: ["Greek"], meaning: "Victory of the people", styles: ["classic"], traits: ["traditional"], popularityTier: "common" },
  { name: "Maddox", nicknames: ["Mad"], origins: ["Welsh"], meaning: "Son of Madoc", styles: ["modern", "surname-style"], traits: ["strong", "unusual"], popularityTier: "common" },
  { name: "Cayden", nicknames: ["Cade"], origins: ["American (respelled)"], meaning: "Fighter, companion", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "common" },
  { name: "Declan", nicknames: ["Dec"], origins: ["Irish"], meaning: "Man of prayer", styles: ["modern", "international"], traits: ["strong", "established"], popularityTier: "common" },
  { name: "Gage", nicknames: [], origins: ["French"], meaning: "Pledge, oath", styles: ["modern", "short-punchy"], traits: ["strong"], popularityTier: "common" },
  { name: "Peyton", nicknames: [], origins: ["English"], meaning: "Fighting man's estate", styles: ["modern", "surname-style"], traits: ["soft"], popularityTier: "common" },
  { name: "Jorge", nicknames: [], origins: ["Spanish"], meaning: "Farmer", styles: ["international"], traits: ["elegant"], popularityTier: "common" },
  { name: "Seth", nicknames: [], origins: ["Hebrew"], meaning: "Appointed", styles: ["biblical", "short-punchy"], traits: ["soft"], popularityTier: "common" },
  { name: "Abraham", nicknames: ["Abe"], origins: ["Hebrew"], meaning: "Father of many", styles: ["biblical", "vintage"], traits: ["traditional", "established"], popularityTier: "common" },
  { name: "Derek", nicknames: ["Rick"], origins: ["German"], meaning: "Ruler of the people", styles: ["classic"], traits: ["strong"], popularityTier: "common" },
  { name: "Bradley", nicknames: ["Brad"], origins: ["English"], meaning: "Broad meadow", styles: ["classic", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Eduardo", nicknames: ["Edu", "Lalo"], origins: ["Spanish"], meaning: "Wealthy guardian", styles: ["international", "classic"], traits: ["elegant"], popularityTier: "common" },
  { name: "Greyson", nicknames: ["Grey"], origins: ["English"], meaning: "Son of the steward", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Collin", nicknames: ["Col"], origins: ["Irish"], meaning: "Young cub", styles: ["classic"], traits: ["soft"], popularityTier: "common" },
  { name: "Andres", nicknames: ["Andy"], origins: ["Spanish"], meaning: "Manly, brave", styles: ["international", "classic"], traits: ["strong"], popularityTier: "common" },
  { name: "Trevor", nicknames: ["Trev"], origins: ["Welsh"], meaning: "Large settlement", styles: ["classic", "modern"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Conner", nicknames: ["Con"], origins: ["Irish"], meaning: "Lover of hounds", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Calvin", nicknames: ["Cal"], origins: ["Latin"], meaning: "Bald", styles: ["classic", "short-punchy"], traits: ["soft", "established"], popularityTier: "common" },
  { name: "Tucker", nicknames: ["Tuck"], origins: ["English"], meaning: "Fabric fuller", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "common" },
  { name: "Javier", nicknames: ["Javi"], origins: ["Spanish"], meaning: "New house, bright", styles: ["international"], traits: ["strong", "elegant"], popularityTier: "common" },
  { name: "Avery", nicknames: ["Ave"], origins: ["English"], meaning: "Ruler of the elves", styles: ["modern", "surname-style"], traits: ["soft"], popularityTier: "common" },
  { name: "Cristian", nicknames: ["Cris"], origins: ["Latin"], meaning: "Follower of Christ", styles: ["international", "biblical"], traits: ["traditional"], popularityTier: "common" },
  { name: "Jaiden", nicknames: ["Jai"], origins: ["American (respelled)"], meaning: "Thankful", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "uncommon" },
  { name: "Rylan", nicknames: ["Ry"], origins: ["English"], meaning: "Island meadow", styles: ["modern", "surname-style"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Francisco", nicknames: ["Paco", "Cisco"], origins: ["Spanish"], meaning: "Free man", styles: ["international"], traits: ["elegant"], popularityTier: "uncommon" },
  { name: "Ricardo", nicknames: ["Rico"], origins: ["Spanish"], meaning: "Brave ruler", styles: ["international"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Jayce", nicknames: [], origins: ["American (invented)"], meaning: "Healer", styles: ["invented", "modern", "short-punchy"], traits: ["unusual"], popularityTier: "uncommon" },
  { name: "Travis", nicknames: ["Trav"], origins: ["French"], meaning: "Crossing, tollgate", styles: ["classic", "modern"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Garrett", nicknames: ["Gary"], origins: ["English"], meaning: "Spear strength", styles: ["classic", "surname-style"], traits: ["strong", "established"], popularityTier: "uncommon" },
  { name: "Jameson", nicknames: ["Jamie"], origins: ["English"], meaning: "Son of James", styles: ["surname-style", "classic"], traits: ["strong", "established"], popularityTier: "uncommon" },
  { name: "Everett", nicknames: ["Ev", "Rhett"], origins: ["English"], meaning: "Brave as a wild boar", styles: ["vintage", "surname-style"], traits: ["soft", "established"], popularityTier: "uncommon" },
  { name: "Fernando", nicknames: ["Nando"], origins: ["Spanish"], meaning: "Adventurous, bold", styles: ["international"], traits: ["strong", "elegant"], popularityTier: "uncommon" },
  { name: "Damien", nicknames: ["Dame"], origins: ["Greek"], meaning: "To tame, subdue", styles: ["classic", "strong"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Erick", nicknames: ["Rick"], origins: ["Scandinavian"], meaning: "Eternal ruler", styles: ["classic"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Josue", nicknames: [], origins: ["Hebrew", "Spanish"], meaning: "The Lord is salvation", styles: ["biblical", "international"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Stephen", nicknames: ["Steve", "Stevie"], origins: ["Greek"], meaning: "Crown", styles: ["classic"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Maximus", nicknames: ["Max"], origins: ["Latin"], meaning: "Greatest", styles: ["classic", "strong"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Cesar", nicknames: [], origins: ["Latin"], meaning: "Long-haired", styles: ["international", "strong"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Manuel", nicknames: ["Manny"], origins: ["Hebrew", "Spanish"], meaning: "God is with us", styles: ["international", "biblical"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Brantley", nicknames: ["Brant"], origins: ["English"], meaning: "Burnt land, fiery torch", styles: ["modern", "surname-style"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Israel", nicknames: ["Izzy"], origins: ["Hebrew"], meaning: "Wrestles with God", styles: ["biblical", "international"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Mario", nicknames: [], origins: ["Latin"], meaning: "Manly", styles: ["international", "classic"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Xander", nicknames: [], origins: ["Greek"], meaning: "Defender of the people", styles: ["modern", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Alexis", nicknames: ["Alex", "Lex"], origins: ["Greek"], meaning: "Defender, helper", styles: ["classic", "international"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Edwin", nicknames: ["Ed", "Eddie"], origins: ["English"], meaning: "Wealthy friend", styles: ["vintage", "classic"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Griffin", nicknames: ["Griff"], origins: ["Welsh"], meaning: "Strong lord", styles: ["modern", "literary"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Corbin", nicknames: ["Corb"], origins: ["French"], meaning: "Raven", styles: ["modern", "surname-style", "nature"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Jeffrey", nicknames: ["Jeff"], origins: ["German"], meaning: "Peaceful pledge", styles: ["classic"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Jaylen", nicknames: ["Jay"], origins: ["American (invented)"], meaning: "Calm", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "uncommon" },
  { name: "Gael", nicknames: [], origins: ["Breton"], meaning: "Generous", styles: ["international", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Jase", nicknames: [], origins: ["American (invented)"], meaning: "Healer", styles: ["invented", "modern", "short-punchy"], traits: ["unusual"], popularityTier: "uncommon" },
  { name: "Trenton", nicknames: ["Trent"], origins: ["English"], meaning: "Trent's town", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Edgar", nicknames: ["Ed"], origins: ["English"], meaning: "Wealthy spearman", styles: ["vintage", "literary"], traits: ["traditional", "unusual"], popularityTier: "uncommon" },
  { name: "Hector", nicknames: [], origins: ["Greek"], meaning: "Steadfast, holding fast", styles: ["classic", "literary", "international"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Lukas", nicknames: ["Luke"], origins: ["German", "Greek"], meaning: "Light-giving", styles: ["classic", "international"], traits: ["soft", "established"], popularityTier: "uncommon" },
  { name: "Johnathan", nicknames: ["Jon", "Johnny"], origins: ["Hebrew"], meaning: "Gift of God", styles: ["classic", "biblical"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Myles", nicknames: [], origins: ["Latin"], meaning: "Soldier", styles: ["classic", "short-punchy"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Keegan", nicknames: ["Keg"], origins: ["Irish"], meaning: "Small, fiery one", styles: ["modern", "international"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Landen", nicknames: ["Land"], origins: ["English"], meaning: "Long hill", styles: ["modern", "surname-style"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Donovan", nicknames: ["Don", "Van"], origins: ["Irish"], meaning: "Dark warrior", styles: ["modern", "surname-style"], traits: ["strong", "established"], popularityTier: "uncommon" },
  { name: "Chance", nicknames: [], origins: ["English"], meaning: "Good fortune", styles: ["modern", "short-punchy"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Braden", nicknames: ["Brady"], origins: ["Irish"], meaning: "Broad hill", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Martin", nicknames: ["Marty"], origins: ["Latin"], meaning: "Of Mars, warlike", styles: ["classic"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Jared", nicknames: [], origins: ["Hebrew"], meaning: "Descent", styles: ["classic", "biblical"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Shawn", nicknames: [], origins: ["Irish"], meaning: "God is gracious", styles: ["classic"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "Charlie", nicknames: [], origins: ["German"], meaning: "Free man", styles: ["classic", "short-punchy"], traits: ["soft", "established"], popularityTier: "uncommon" },
  { name: "Clayton", nicknames: ["Clay"], origins: ["English"], meaning: "Settlement on clay land", styles: ["classic", "surname-style"], traits: ["strong", "established"], popularityTier: "uncommon" },
  { name: "Andy", nicknames: [], origins: ["Greek"], meaning: "Manly, brave", styles: ["classic", "short-punchy"], traits: ["soft"], popularityTier: "uncommon" },
  { name: "King", nicknames: [], origins: ["English"], meaning: "King", styles: ["invented", "strong", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Troy", nicknames: [], origins: ["Greek"], meaning: "Ancient city name", styles: ["classic", "short-punchy"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Sergio", nicknames: [], origins: ["Latin"], meaning: "Servant, attendant", styles: ["international"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Marco", nicknames: [], origins: ["Italian"], meaning: "Dedicated to Mars", styles: ["international"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Drake", nicknames: [], origins: ["English"], meaning: "Dragon", styles: ["modern", "strong", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Erik", nicknames: [], origins: ["Scandinavian"], meaning: "Eternal ruler", styles: ["classic", "international"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Dalton", nicknames: ["Dal"], origins: ["English"], meaning: "Valley town", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Zander", nicknames: [], origins: ["Greek"], meaning: "Defender of the people", styles: ["modern", "short-punchy"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Kameron", nicknames: ["Kam"], origins: ["Scottish"], meaning: "Crooked nose", styles: ["modern", "surname-style"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Dominick", nicknames: ["Dom"], origins: ["Latin"], meaning: "Belonging to the Lord", styles: ["classic", "biblical"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Tyson", nicknames: ["Ty"], origins: ["English"], meaning: "Firebrand, son of Denys", styles: ["modern", "strong"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Brendan", nicknames: ["Bren"], origins: ["Irish"], meaning: "Prince, sword", styles: ["classic", "international"], traits: ["strong", "established"], popularityTier: "uncommon" },
  { name: "Johnny", nicknames: [], origins: ["Hebrew"], meaning: "God is gracious", styles: ["classic", "short-punchy"], traits: ["soft", "established"], popularityTier: "uncommon" },
  { name: "Kyler", nicknames: ["Ky"], origins: ["English"], meaning: "Archer", styles: ["modern", "invented"], traits: ["unusual"], popularityTier: "uncommon" },
  { name: "Caiden", nicknames: ["Cade"], origins: ["American (respelled)"], meaning: "Fighter, companion", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "uncommon" },
  { name: "Rowan", nicknames: ["Row"], origins: ["Irish"], meaning: "Little redhead", styles: ["modern", "nature", "international"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Gregory", nicknames: ["Greg"], origins: ["Greek"], meaning: "Watchful, alert", styles: ["classic"], traits: ["traditional"], popularityTier: "uncommon" },
  { name: "Dawson", nicknames: ["Daw"], origins: ["English"], meaning: "Son of David", styles: ["modern", "surname-style"], traits: ["strong", "established"], popularityTier: "uncommon" },
  { name: "Paxton", nicknames: ["Pax"], origins: ["English"], meaning: "Peaceful town", styles: ["modern", "surname-style"], traits: ["soft", "unusual"], popularityTier: "uncommon" },
  { name: "Drew", nicknames: [], origins: ["Greek"], meaning: "Manly, brave", styles: ["classic", "short-punchy"], traits: ["soft", "established"], popularityTier: "uncommon" },
  { name: "Roberto", nicknames: ["Beto"], origins: ["Italian", "Spanish"], meaning: "Bright fame", styles: ["international"], traits: ["strong"], popularityTier: "uncommon" },
  { name: "Dante", nicknames: [], origins: ["Italian"], meaning: "Everlasting", styles: ["international", "literary"], traits: ["strong", "elegant"], popularityTier: "uncommon" },
  { name: "Emilio", nicknames: [], origins: ["Italian", "Spanish"], meaning: "Rival, eager", styles: ["international"], traits: ["elegant"], popularityTier: "uncommon" },
  { name: "Dakota", nicknames: ["Kota"], origins: ["Native American"], meaning: "Friend, ally", styles: ["modern", "nature"], traits: ["strong", "unusual"], popularityTier: "uncommon" },
  { name: "Braylon", nicknames: ["Bray"], origins: ["American (invented)"], meaning: "Modern coinage", styles: ["invented", "modern"], traits: ["unusual"], popularityTier: "uncommon" },
];
